Name:           perl-Pod-Weaver
Version:        3.101638
Release:        1%{?dist}
Summary:        Weave together a Pod document from an outline
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Pod-Weaver/
Source0:        http://www.cpan.org/modules/by-module/Pod/Pod-Weaver-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Config::MVP) >= 2
BuildRequires:  perl(Config::MVP::Assembler)
BuildRequires:  perl(Config::MVP::Assembler::WithBundles)
BuildRequires:  perl(Config::MVP::Reader::Finder)
BuildRequires:  perl(Config::MVP::Reader::INI)
BuildRequires:  perl(DateTime)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(List::MoreUtils)
BuildRequires:  perl(Log::Dispatchouli) >= 1.100710
BuildRequires:  perl(Moose)
BuildRequires:  perl(Moose::Autobox) >= 0.10
BuildRequires:  perl(Moose::Role)
BuildRequires:  perl(namespace::autoclean)
BuildRequires:  perl(Params::Util)
BuildRequires:  perl(Pod::Elemental) >= 0.100220
BuildRequires:  perl(Pod::Elemental::Document)
BuildRequires:  perl(Pod::Elemental::Element::Nested)
BuildRequires:  perl(Pod::Elemental::Element::Pod5::Command)
BuildRequires:  perl(Pod::Elemental::Element::Pod5::Ordinary)
BuildRequires:  perl(Pod::Elemental::Element::Pod5::Region)
BuildRequires:  perl(Pod::Elemental::Element::Pod5::Verbatim)
BuildRequires:  perl(Pod::Elemental::Selectors)
BuildRequires:  perl(Pod::Elemental::Transformer::Gatherer)
BuildRequires:  perl(Pod::Elemental::Transformer::Nester)
BuildRequires:  perl(Pod::Elemental::Transformer::Pod5)
BuildRequires:  perl(Pod::Elemental::Types)
BuildRequires:  perl(PPI)
BuildRequires:  perl(Software::License::Artistic_1_0)
BuildRequires:  perl(Software::License::Perl_5)
BuildRequires:  perl(String::Flogger) >= 1
BuildRequires:  perl(String::Formatter) >= 0.100680
BuildRequires:  perl(String::RewritePrefix)
BuildRequires:  perl(Test::Differences)
BuildRequires:  perl(Test::More) >= 0.96
Requires:       perl(Config::MVP) >= 2
Requires:       perl(Config::MVP::Assembler)
Requires:       perl(Config::MVP::Assembler::WithBundles)
Requires:       perl(Config::MVP::Reader::Finder)
Requires:       perl(Config::MVP::Reader::INI)
Requires:       perl(DateTime)
Requires:       perl(File::Spec)
Requires:       perl(List::MoreUtils)
Requires:       perl(Log::Dispatchouli) >= 1.100710
Requires:       perl(Moose)
Requires:       perl(Moose::Autobox) >= 0.10
Requires:       perl(Moose::Role)
Requires:       perl(namespace::autoclean)
Requires:       perl(Params::Util)
Requires:       perl(Pod::Elemental) >= 0.100220
Requires:       perl(Pod::Elemental::Document)
Requires:       perl(Pod::Elemental::Element::Nested)
Requires:       perl(Pod::Elemental::Element::Pod5::Command)
Requires:       perl(Pod::Elemental::Element::Pod5::Ordinary)
Requires:       perl(Pod::Elemental::Element::Pod5::Region)
Requires:       perl(Pod::Elemental::Element::Pod5::Verbatim)
Requires:       perl(Pod::Elemental::Selectors)
Requires:       perl(Pod::Elemental::Transformer::Gatherer)
Requires:       perl(Pod::Elemental::Transformer::Nester)
Requires:       perl(Pod::Elemental::Transformer::Pod5)
Requires:       perl(Pod::Elemental::Types)
Requires:       perl(String::Flogger) >= 1
Requires:       perl(String::Formatter) >= 0.100680
Requires:       perl(String::RewritePrefix)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Pod::Weaver is a system for building Pod documents from templates. It
doesn't perform simple text substitution, but instead builds a
Pod::Elemental::Document. Its plugins sketch out a series of sections that
will be produced based on an existing Pod document or other provided
information.

%prep
%setup -q -n Pod-Weaver-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes dist.ini LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Nov 27 2012 João Costa <joaocosta@zonalivre.org> 3.101638-1
- Specfile autogenerated by cpanspec 1.78.
