Name:           perl-Math-Combinatorics
Version:        0.09
Release:        2%{?dist}
Summary:        Perform combinations and permutations on lists
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Math-Combinatorics/
Source0:        http://www.cpan.org/authors/id/A/AL/ALLENDAY/Math-Combinatorics-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::More)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Combinatorics is the branch of mathematics studying the enumeration,
combination, and permutation of sets of elements and the
mathematical relations that characterize their properties.

%prep
%setup -q -n Math-Combinatorics-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sun Nov 18 2012 João Costa <joaocosta@zonalivre.org> 0.09-2
- Update license

* Sun Nov 11 2012 João Costa <joaocosta@zonalivre.org> 0.09-1
- Specfile autogenerated by cpanspec 1.78.
