Name:           perl-Devel-SimpleTrace
Version:        0.08
Release:        1%{?dist}
Summary:        See where you code warns and dies using stack traces
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Devel-SimpleTrace/
Source0:        http://www.cpan.org/modules/by-module/Devel/Devel-SimpleTrace-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Data::Dumper)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Test::More)
Requires:       perl(Data::Dumper)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module can be used to more easily spot the place where a program or a
module generates errors. Its use is extremely simple, reduced to just
useing it.

%prep
%setup -q -n Devel-SimpleTrace-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes eg LICENSE LICENSE.Artistic LICENSE.GPL README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Jan 03 2014 João Costa <joaocosta@zonalivre.org> 0.08-1
- Specfile autogenerated by cpanspec 1.78.
