Name:           perl-Finance-HostedTrader-UI
Version:        0.03
Release:        2%{?dist}
Summary:        Catalyst based application
License:        MIT
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Finance-HostedTrader-UI/
Source0:        http://www.cpan.org/modules/by-module/Finance/Finance-HostedTrader-UI-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Catalyst::Action::RenderView)
BuildRequires:  perl(Catalyst::Model::DBIC::Schema)
BuildRequires:  perl(Catalyst::Plugin::ConfigLoader)
BuildRequires:  perl(Catalyst::Plugin::Static::Simple)
BuildRequires:  perl(Catalyst::Runtime) >= 5.80013
BuildRequires:  perl(Catalyst::View::TT)
BuildRequires:  perl(Config::General)
BuildRequires:  perl(CPAN)
BuildRequires:  perl(ExtUtils::MakeMaker) >= 6.42
BuildRequires:  perl(File::Copy::Recursive)
BuildRequires:  perl(Finance::HostedTrader)
BuildRequires:  perl(JSON)
BuildRequires:  perl(parent)
Requires:       perl(Catalyst::Action::RenderView)
Requires:       perl(Catalyst::Model::DBIC::Schema)
Requires:       perl(Catalyst::Plugin::ConfigLoader)
Requires:       perl(Catalyst::Plugin::Static::Simple)
Requires:       perl(Catalyst::Runtime) >= 5.80013
Requires:       perl(Catalyst::View::TT)
Requires:       perl(Config::General)
# cpan2spec added the CPAN dependency but I'm commenting it out, think it might only be required in dev (puppet installs it in dev anyway)
#Requires:       perl(CPAN)
Requires:       perl(ExtUtils::MakeMaker) >= 6.42
Requires:       perl(File::Copy::Recursive)
Requires:       perl(Finance::HostedTrader)
Requires:       perl(JSON)
Requires:       perl(parent)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
fxhistoricaldata.com website app

%prep
%setup -q -n Finance-HostedTrader-UI-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes finance_hostedtrader_ui.conf README.md
%{perl_vendorlib}/*
%{_mandir}/man3/*
%{_mandir}/man1/*
/usr/bin/finance_hostedtrader_ui_cgi.pl
/usr/bin/finance_hostedtrader_ui_create.pl
/usr/bin/finance_hostedtrader_ui_fastcgi.pl
/usr/bin/finance_hostedtrader_ui_server.pl
/usr/bin/finance_hostedtrader_ui_test.pl

%changelog
* Sat Feb 23 2013 João Costa <joaocosta@zonalivre.org> 0.03-1
- API change, make list of symbols optional in the /signal/parse handler
- JSONP support for /signal/parse

* Fri Nov 30 2012 João Costa <joaocosta@zonalivre.org> 0.02-2
- Remove symbols which don't exist in the fxcm db

* Sat Nov 24 2012 João Costa <joaocosta@zonalivre.org> 0.01-2
- Update hardcoded download path

* Sat Nov 24 2012 João Costa <joaocosta@zonalivre.org> 0.01-1
- Specfile autogenerated by cpanspec 1.78.
