Name:           perl-Dist-Zilla-Plugin-Config-Git
Version:        0.92
Release:        1%{?dist}
Summary:        Plugin configuration containing settings for a Git repo
License:        Artistic 2.0
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Dist-Zilla-Plugin-Config-Git/
Source0:        http://www.cpan.org/modules/by-module/Dist/Dist-Zilla-Plugin-Config-Git-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 1:v5.10.1
BuildRequires:  perl(Dist::Zilla::Role::Plugin) >= 1.000
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Moose) >= 0.34
BuildRequires:  perl(MooseX::Types) >= 0.06
BuildRequires:  perl(namespace::clean) >= 0.06
BuildRequires:  perl(String::Errf) >= 0.001
BuildRequires:  perl(Test::CheckDeps) >= 0.010
BuildRequires:  perl(Test::More) >= 0.94
Requires:       perl(Dist::Zilla::Role::Plugin) >= 1.000
Requires:       perl(Moose) >= 0.34
Requires:       perl(MooseX::Types) >= 0.06
Requires:       perl(namespace::clean) >= 0.06
Requires:       perl(String::Errf) >= 0.001
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This is a configuration plugin for Git repo/branch information. A
configuration plugin is sort of like a Stash, but is better suited for intra-
plugin data sharing, using distro (not user) data.

%prep
%setup -q -n Dist-Zilla-Plugin-Config-Git-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc CHANGES dist.ini LICENSE META.json README README.html
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Jan 03 2014 João Costa <joaocosta@zonalivre.org> 0.92-1
- Specfile autogenerated by cpanspec 1.78.
