Name:           perl-MooseX-AttributeShortcuts
Version:        0.017
Release:        1%{?dist}
Summary:        Shorthand for common attribute options
License:        LGPLv2+
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/MooseX-AttributeShortcuts/
Source0:        http://www.cpan.org/authors/id/R/RS/RSRCHBOY/MooseX-AttributeShortcuts-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.006
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Moose)
BuildRequires:  perl(Moose::Exporter)
BuildRequires:  perl(Moose::Role)
BuildRequires:  perl(Moose::Util::MetaRole)
BuildRequires:  perl(Moose::Util::TypeConstraints)
BuildRequires:  perl(MooseX::Role::Parameterized)
BuildRequires:  perl(MooseX::Types::Common::String)
BuildRequires:  perl(MooseX::Types::Moose)
BuildRequires:  perl(namespace::autoclean)
BuildRequires:  perl(Test::Fatal)
BuildRequires:  perl(Test::Moose)
BuildRequires:  perl(Test::Moose::More) >= 0.017
BuildRequires:  perl(Test::More) >= 0.88
Requires:       perl(Moose)
Requires:       perl(Moose::Exporter)
Requires:       perl(Moose::Util::MetaRole)
Requires:       perl(Moose::Util::TypeConstraints)
Requires:       perl(MooseX::Role::Parameterized)
Requires:       perl(MooseX::Types::Common::String)
Requires:       perl(MooseX::Types::Moose)
Requires:       perl(namespace::autoclean)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Ever find yourself repeatedly specifying writers and builders, because
there's no good shortcut to specifying them? Sometimes you want an
attribute to have a read-only public interface, but a private writer. And
wouldn't it be easier to just say "builder => 1" and have the attribute
construct the canonical "_build_$name" builder name for you?

%prep
%setup -q -n MooseX-AttributeShortcuts-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes dist.ini LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Nov 29 2012 João Costa <joaocosta@zonalivre.org> 0.017-1
- Specfile autogenerated by cpanspec 1.78.
