Name:           perl-Test-Moose-More
Version:        0.017
Release:        1%{?dist}
Summary:        More tools for testing Moose packages
License:        LGPLv2+
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Test-Moose-More/
Source0:        http://www.cpan.org/authors/id/R/RS/RSRCHBOY/Test-Moose-More-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.006
BuildRequires:  perl(Data::OptList)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Moose)
BuildRequires:  perl(Moose::Autobox)
BuildRequires:  perl(Moose::Role)
BuildRequires:  perl(Moose::Util)
BuildRequires:  perl(Moose::Util::TypeConstraints)
BuildRequires:  perl(namespace::autoclean)
BuildRequires:  perl(Perl6::Junction)
BuildRequires:  perl(Scalar::Util)
BuildRequires:  perl(Sub::Exporter)
BuildRequires:  perl(TAP::SimpleOutput)
BuildRequires:  perl(Test::Builder)
BuildRequires:  perl(Test::Builder::Tester)
BuildRequires:  perl(Test::Moose)
BuildRequires:  perl(Test::More) >= 0.88
Requires:       perl(Data::OptList)
Requires:       perl(Moose::Autobox)
Requires:       perl(Moose::Util)
Requires:       perl(Moose::Util::TypeConstraints)
Requires:       perl(Perl6::Junction)
Requires:       perl(Scalar::Util)
Requires:       perl(Sub::Exporter)
Requires:       perl(Test::Builder)
Requires:       perl(Test::Moose)
Requires:       perl(Test::More)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This package contains a number of additional tests that can be employed
against Moose classes/roles. It is intended to replace Test::Moose in your
tests, and reexports any tests that it has and we do not, yet.

%prep
%setup -q -n Test-Moose-More-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes dist.ini LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Nov 29 2012 João Costa <joaocosta@zonalivre.org> 0.017-1
- Specfile autogenerated by cpanspec 1.78.
