Name:           perl-Pod-Elemental-Transformer-List
Version:        0.102000
Release:        1%{?dist}
Summary:        Pod::Elemental::Transformer::List Perl module
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Pod-Elemental-Transformer-List/
Source0:        http://www.cpan.org/modules/by-module/Pod/Pod-Elemental-Transformer-List-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Moose)
BuildRequires:  perl(namespace::autoclean)
BuildRequires:  perl(Pod::Elemental)
BuildRequires:  perl(Pod::Elemental::Element::Pod5::Command)
BuildRequires:  perl(Pod::Elemental::Transformer) >= 0.101620
BuildRequires:  perl(Pod::Elemental::Transformer::Pod5)
BuildRequires:  perl(Pod::Elemental::Types)
BuildRequires:  perl(Test::Differences)
BuildRequires:  perl(Test::More) >= 0.96
Requires:       perl(Moose)
Requires:       perl(namespace::autoclean)
Requires:       perl(Pod::Elemental::Element::Pod5::Command)
Requires:       perl(Pod::Elemental::Transformer) >= 0.101620
Requires:       perl(Pod::Elemental::Types)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Pod::Elemental::Transformer::List Perl module

%prep
%setup -q -n Pod-Elemental-Transformer-List-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes dist.ini LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Jan 03 2014 João Costa <joaocosta@zonalivre.org> 0.102000-1
- Specfile autogenerated by cpanspec 1.78.
