Name:           perl-Games-Word
Version:        0.06
Release:        1%{?dist}
Summary:        Utility functions for writing word games
License:        GPL+
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Games-Word/
Source0:        http://www.cpan.org/authors/id/D/DO/DOY/Games-Word-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(List::MoreUtils)
BuildRequires:  perl(Math::Combinatorics)
BuildRequires:  perl(Test::Deep)
BuildRequires:  perl(Test::Deep::NoTest)
BuildRequires:  perl(Test::Fatal)
BuildRequires:  perl(Test::More) >= 0.88
Requires:       perl(List::MoreUtils)
Requires:       perl(Math::Combinatorics)
Requires:       perl(Test::Deep::NoTest)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Games::Word provides several utility functions for writing word games, such
as manipulating permutations of strings, testing for similarity of strings,
and finding strings from a given source of characters.

%prep
%setup -q -n Games-Word-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes dist.ini LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man1/*
%{_mandir}/man3/*
/usr/bin/cryptogram.pl
/usr/bin/jotto.pl
/usr/bin/mastermind.pl
/usr/bin/solve-ghost.pl
/usr/bin/solve-spook.pl
/usr/bin/solve-superghost.pl
/usr/bin/solve-xghost.pl


%changelog
* Sun Nov 11 2012 João Costa <joaocosta@zonalivre.org> 0.06-1
- Specfile autogenerated by cpanspec 1.78.
