#!/bin/bash

set -e

wget -q -N http://ftp.up.pt/fedora/releases/20/Fedora/x86_64/os/isolinux/vmlinuz
wget -q -N http://ftp.up.pt/fedora/releases/20/Fedora/x86_64/os/isolinux/initrd.img

cp initrd.img initrd_ks.img
echo ks.cfg | cpio -c -o >> initrd_ks.img

if [ ! -f system.raw ]; then
    dd if=/dev/zero of=system.raw bs=1024M count=5
fi

if [ ! -f data.raw ]; then
    dd if=/dev/zero of=data.raw bs=1024M count=20
fi

sudo qemu-system-x86_64     \
        -hda system.raw     \
        -hdb data.raw       \
        -net nic -net user  \
        -m 1024M            \
        -localtime          \
        -enable-kvm         \
        -nographic          \
        -no-reboot          \
        -kernel vmlinuz     \
        -initrd initrd_ks.img   \
        -append "ks=file:///ks.cfg console=ttyS0 panic=1"
