#!/bin/bash

# What - Creates raw disk images with a minimal CentOS 6 installed ( from http://mirror.centos.org )
# Why  - A minimal system can be used to bootstrap software projects
# When - Run this to boot a new system with nothing but the bare minimum on it
# How  - Downloads pxeboot kernel+initrd.img, injects a minimal install kickstart file in initrd.img, starts a VM under qemu booting from ROM using the downloaded kernel. Once the systems boots, it will run a netinstall based on the provided kickstart file.
# Who  - 

set -e
set -x

wget -N http://mirror.centos.org/centos/6/os/x86_64/images/pxeboot/vmlinuz
wget -N http://mirror.centos.org/centos/6/os/x86_64/images/pxeboot/initrd.img

rm -f initrd_ks
cp initrd.img initrd_ks.img
unlzma -S .img initrd_ks.img
echo ks.cfg | cpio -c -o >> initrd_ks
lzma -S .img initrd_ks

if [ ! -f system.raw ]; then
    dd if=/dev/zero of=system.raw bs=1024M count=5
fi

if [ ! -f data.raw ]; then
    dd if=/dev/zero of=data.raw bs=1024M count=8
fi


sudo qemu-system-x86_64     \
        -hda system.raw     \
        -hdb data.raw       \
        -net nic -net user  \
        -m 1024M            \
        -localtime          \
        -enable-kvm         \
        -no-reboot          \
        -kernel vmlinuz     \
        -initrd initrd_ks.img   \
        -append "ks=file:///ks.cfg console=ttyS0 panic=1" \
        -nographic
