#!/bin/bash

# What - Install fx_trader specific packages
# Why  -
# When - After general setup, before the system can be used
# How  - The script tries to be idempotent, so it can be run over and over again with no side effects.
# Who  - 

set -e
set -x

### Personal dev setup
mkdir -p ~/src

# The first time git connects to github.com over ssh, it will ask for manual confirmation of the host key
# This ssh wrapper prevents that
echo '/usr/bin/ssh -o StrictHostKeyChecking=no $@'> /tmp/gitssh
chmod +x /tmp/gitssh

sudo service mysqld restart

### lib mysqludf ta
if [ ! -d ~/src/lib_mysqludf_ta ]; then
    cd ~/src
    GIT_SSH="/tmp/gitssh" git clone git@github.com:joaocosta/lib_mysqludf_ta.git
    cd ~/src/lib_mysqludf_ta
    ./configure
    make
    sudo make install
fi


for udf_create_file in ~/src/lib_mysqludf_ta/setup/*up; do
    udf_name=$(basename $udf_create_file)
    udf_name=${udf_name:13}
    udf_name=${udf_name%_*}
    if test $(mysql -N -uroot -e "select count(1) from mysql.func where name = '${udf_name}'") -ne 1; then
        echo Installing UDF $udf_name
        mysql -uroot < $udf_create_file
    fi
done




### lib ForexConnect (FXCM API) ###
curl http://fxcodebase.com/bin/forexconnect/1.3.2/ForexConnectAPI-1.3.2-Linux-x86_64.tar.gz | sudo tar zxf - -C ~/
sudo cp -R ~/ForexConnectAPI-1.3.2-Linux-x86_64/include/* /usr/include/.
sudo cp -R ~/ForexConnectAPI-1.3.2-Linux-x86_64/lib/* /usr/lib64/.

### Finance::FXCM::Simple
cd ~/src
if [ ! -d ~/src/Finance-FXCM-Simple ]; then
    GIT_SSH="/tmp/gitssh" git clone git@github.com:joaocosta/Finance-FXCM-Simple.git
    cd ~/src/Finance-FXCM-Simple
else
    cd ~/src/Finance-FXCM-Simple
    git pull
fi
cpanm --sudo -v --installdeps --notest .
dzil authordeps | cpanm --sudo
perl Makefile.PL
make test && sudo make install

### Finance::HostedTrader

mysql -u root -e 'create database if not exists fxcm'

if test $(mysql -N -uroot -e "select count(1) from mysql.user where user = 'fxcm'") -eq 0; then
    mysql -u root -e "CREATE USER 'fxcm'@'localhost' IDENTIFIED BY 'fxcm'"
    mysql -u root -e "GRANT ALL PRIVILEGES ON fxcm.* TO 'fxcm'@'localhost'"
    mysqladmin -u root flush-privileges
fi

cd ~/src
if [ ! -d ~/src/Finance-HostedTrader ]; then
    GIT_SSH="/tmp/gitssh" git clone https://github.com/joaocosta/Finance-HostedTrader
    cd ~/src/Finance-HostedTrader
else
    cd ~/src/Finance-HostedTrader
    git pull
fi
sudo cp -R etc/fxtrader /etc
dzil authordeps | cpanm --sudo
cpanm --sudo Pod::Elemental::Transformer::List

rm -fR Finance-HostedTrader-*
dzil build
cd Finance-HostedTrader-*
cpanm --sudo -v --installdeps --notest .
PERL5LIB=lib bin/fx-create-db-schema.pl | mysql -u fxcm -pfxcm fxcm
PERL5LIB=lib PATH=$PATH:bin perl t/data/loadTestData.sh ../t/data
perl Makefile.PL
make test && sudo make install
