#!/bin/bash

# What - Setup post installation, so that users can ssh to minimal system
# Why  - Bootstrap installation only creates a minimal with root only account. By default, root can't ssh.
# When - After bootstrap, before the system can be used
# How  -
# Who  - 

set -e
set -x

echo "%wheel        ALL=(ALL)       NOPASSWD: ALL" > /etc/sudoers.d/001_wheel_sudo
chmod 660 /etc/sudoers.d/001_wheel_sudo

useradd -m joao
usermod -G wheel -a joao
mkdir /home/joao/.ssh
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6hE75Ox6wDfXVJzXeKdyUBO4o19TtGxboJTI2vR3CE9ZJbODIxSr+tfMZcwmuSF892PiahhVzAA2wJ6LdMtFH6FUIGvjU0i7jIo/x+TmvheH46N9qllo2C2ZlxL/HbpRYIyqEntUYcBQzYBvUwnzoDFgS1GhG4LalYp0U9zlHGOA/Wk7qBjH8Ca1mtPSnxudsb/NwERIjfLbvdX9Fc+vkx6fs3ykJv+p8lPEZkw3kcVAfuyhnXzE7kprSHDuOuQo0FDvCTjy9ISxZPvExKT7bD7vQRlrx9PLzYSWI7/evonWHR8c/jPS8U56ii8YH/rtC/iqo4LiwKFxoxaDdS2wD joaocosta@zonalivre.org" > /home/joao/.ssh/authorized_keys
chown -R joao: /home/joao/.ssh
chmod 700 /home/joao/.ssh
chmod 600 /home/joao/.ssh/authorized_keys


### Personal dev setup

git config --global user.name "Joao Costa"
git config --global user.email "joaocosta@zonalivre.org"
mkdir ~/src

### lib mysqludf ta
cd ~/src
git clone git@github.com:joaocosta/lib_mysqludf_ta.git
cd ~/src/lib_mysqludf_ta
./configure
make
sudo make install


for file in ~/src/libmysqludf_ta/setup/*up; do
  mysql -uroot < $file
done


### lib ForexConnect (FXCM API) ###
curl http://fxcodebase.com/bin/forexconnect/1.3.2/ForexConnectAPI-1.3.2-Linux-x86_64.tar.gz | tar zxf - -C ~


### Finance::FXCM::Simple
cd ~/src
git clone git@github.com:joaocosta/Finance-FXCM-Simple.git
cd ~/src/Finance-FXCM-Simple
sudo cpanm -v --installdeps --notest .
sudo cpanm -v --installdeps --notest Dist::Zilla
dzil authordeps | sudo cpanm
perl Makefile.PL
make
sudo make install

### Finance::FXCM::HostedTrader
cd ~/src
git clone https://github.com/joaocosta/Finance-HostedTrader
cd ~/src/Finance-HostedTrader
dzil authordeps | sudo cpanm
sudo cpanm Pod::Elemental::Transformer::List

dzil test
