#!/bin/bash

set -e


if [ ! -f system.raw ]; then
    zcat system.centos6.gz > system.raw
fi

sudo qemu-system-x86_64 \
    -hda system.raw     \
    -hdb data.raw       \
    -net nic -net user  \
    -m 1024M            \
    -localtime          \
    -enable-kvm         \
    -redir tcp:2222::22 \
    -nographic          \
    -redir tcp:8888::80 \
    -virtfs local,path=/home/joao/src/fx/,security_model=passthrough,mount_tag=host_share 2>&1 > /dev/null < /dev/null &
#sudo rpm -Uvh https://yum.puppetlabs.com/el/5/products/x86_64/puppetlabs-release-5-7.noarch.rpm
#sudo rpm -Uvh http://ftp.fi.muni.cz/pub/linux/fedora/epel/6/i386/epel-release-6-8.noarch.rpm
# mount -t 9p -o trans=virtio host_share /opt/src -oversion=9p2000.L
