# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "Fedora-17-x86_64"
  # config.vm.box_url = "http://domain.com/path/to/above.box"
  # config.vm.boot_mode = :gui

  # Assign this VM to a host-only network IP, allowing you to access it
  # via the IP. Host-only networks can talk to the host machine as well as
  # any other machines on the same network, but cannot be accessed (through this
  # network interface) by any external networks.
  # config.vm.network :hostonly, "192.168.33.10"

  # Assign this VM to a bridged network, allowing you to connect directly to a
  # network using the host's network device. This makes the VM appear as another
  # physical device on your network.
  # config.vm.network :bridged

  # config.vm.forward_port 80, 8080
  config.vm.forward_port 80, 8080
 
  # Share an additional folder to the guest VM. The first argument is
  # an identifier, the second is the path on the guest to mount the
  # folder, and the third is the path on the host to the actual folder.
  # The remaining arguments are optional
  config.vm.share_folder "v-data", "/opt/src", "../../../", :owner => 'joao', :group => 'joao'
  # config.vm.share_folder "v-data", "/vagrant_data", "../data", :create => true, :extra => 'dmode=7777,fmode=7777', :owner => 'user', :group => 'group' 

  # By default, VirtualBox won't allow creation of symlinks in shared folders
  # Change that for the "v-data" share
  config.vm.customize [ "setextradata", :id,
  "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-data", "1"
  ]

  # Customize memory allocated to VM
  #config.vm.customize ["modifyvm", :id, "--memory", 1024]

  config.vm.provision :puppet, :module_path => "../../puppet/modules" do |puppet|
     puppet.manifests_path = "../../puppet/manifests"
     puppet.manifest_file  = "apache.pp"
  end

  config.vm.provision :puppet, :module_path => "../../puppet/modules", :options => "--verbose" do |puppet|
     puppet.manifests_path = "../../puppet/manifests"
     puppet.manifest_file  = "buildbox.pp"
  end
end
