#!/bin/bash

# What - Creates raw disk images with a minimal CentOS 7 installed ( from http://mirror.centos.org )
# Why  - A minimal system can be used to bootstrap software projects
# When - Run this to boot a new system with nothing but the bare minimum on it, ie, the very first thing to do in a new project
# How  - Downloads pxeboot kernel+initrd.img, injects a minimal install kickstart file in initrd.img, starts a VM under qemu booting from ROM using the downloaded kernel. Once the systems boots, it will run a netinstall based on the provided kickstart file.
# Who  - 

set -euo pipefail

echo Fetching kernel and initrd image if needed
wget -N http://mirror.centos.org/centos/7/os/x86_64/images/pxeboot/vmlinuz
wget -N http://mirror.centos.org/centos/7/os/x86_64/images/pxeboot/initrd.img

# Injecting the kickstart file into the initrd image prevents the dependency
# on an external PXE boot or HTTP server to serve the kickstart file
echo Injecting kickstart file in the initrd image.
cp initrd.img initrd_ks.img
echo ks.cfg | cpio -c -o >> initrd_ks.img

if [ ! -f system.qcow2 ]; then
    echo Creating new system image disk file
    qemu-img create -f qcow2 -o preallocation=falloc system.qcow2 10G
else
    echo Reusing existing system image disk file
fi

### Boot from kernel and initrd image which will 
### do an OS install from the provided kickstart file
echo Booting system and installing via kickstart
sudo qemu-system-x86_64     \
        -drive file=system.qcow2,format=qcow2,index=0,media=disk     \
        -net nic -net user  \
        -m 1024M            \
        -localtime          \
        -enable-kvm         \
        -no-reboot          \
        -kernel vmlinuz     \
        -initrd initrd_ks.img   \
        -append "inst.ks=file:/ks.cfg console=ttyS0 panic=1" \
        -nographic
