#!/bin/bash

set -e

# What - Starts a qemu instance in the background
# Why  - So ssh is available and the VM can be used in a running state
# When - When the VM needs to be used, ie, for development
# How  - Starts a VM instance in the background. pid file is written to /var/run
# Who  - 


#    -hda system.raw     \
#    -hdb data.raw       \
sudo qemu-system-x86_64 \
    -drive file=system.raw,format=raw,index=0,media=disk \
    -net nic -net user  \
    -m 1024M            \
    -localtime          \
    -enable-kvm         \
    -redir tcp:2222::22 \
    -redir tcp:8888::80 \
    -redir tcp:3000::3000 \
    -pidfile /var/run/vm2222.pid \
    -virtfs local,path=/home/joao/src/fx/,security_model=passthrough,mount_tag=host_share \
    -daemonize \
    -display none
# mount -t 9p -o trans=virtio host_share /opt/src -oversion=9p2000.L
